import React from 'react';
import { Lightbulb, Search, TrendingUp, Wallet, ShieldCheck, Layers, Send } from 'lucide-react';

const HowToUse: React.FC = () => {
  return (
    <div className="space-y-12">
      <div className="space-y-4 text-center">
        <Lightbulb className="w-16 h-16 text-orange-500 mx-auto" />
        <h2 className="text-4xl font-bold tracking-tight">How to Use FootyEdge AI</h2>
        <p className="text-zinc-400 max-w-2xl mx-auto">
          Welcome to FootyEdge AI! This guide will walk you through the key features and how to leverage
          our artificial intelligence to enhance your football betting strategy.
        </p>
      </div>

      <section className="space-y-6">
        <h3 className="text-2xl font-bold border-b border-zinc-800 pb-2">1. Dashboard Overview</h3>
        <p className="text-zinc-400">
          The Dashboard is your central hub for real-time insights.
        </p>
        <ul className="list-disc list-inside space-y-2 text-zinc-400">
          <li>
            <strong>Telegram Signals:</strong> Join our exclusive Telegram channel for instant value alerts and booking codes.
            Click the "Join Channel" button to get started.
          </li>
          <li>
            <strong>Live Value Alerts:</strong> Keep an eye on the "Live Value Alerts" section for real-time betting inefficiencies.
          </li>
          <li>
            <strong>Today's Matches:</strong> See a curated list of today's matches with quick access to predictions and betting options.
          </li>
          <li>
            <strong>Intelligence Engine:</strong> Select any two teams to generate deep match intelligence, including win probabilities,
            expected goals, and recommended bets.
          </li>
        </ul>
      </section>

      <section className="space-y-6">
        <h3 className="text-2xl font-bold border-b border-zinc-800 pb-2">2. Predictions</h3>
        <p className="text-zinc-400">
          Access a history of recent predictions generated by the AI engine.
        </p>
        <ul className="list-disc list-inside space-y-2 text-zinc-400">
          <li>
            Each prediction card provides detailed probabilities, over/under goals, BTTS stats, and the best value bet.
          </li>
          <li>
            Click "Generate Booking Code" for direct Bet9ja integration.
          </li>
          <li>
            <strong>Premium Signals:</strong> Unlock exclusive, high-confidence predictions by upgrading to a Premium membership.
          </li>
        </ul>
      </section>

      <section className="space-y-6">
        <h3 className="text-2xl font-bold border-b border-zinc-800 pb-2">3. Value Bets</h3>
        <p className="text-zinc-400">
          Discover and manage high Expected Value (EV) bets identified by our AI.
        </p>
        <ul className="list-disc list-inside space-y-2 text-zinc-400">
          <li>
            Use the "Live Scan" button to refresh for the latest value opportunities.
          </li>
          <li>
            Filter bets by "active," "won," "lost," or "all" to review your history.
          </li>
          <li>
            Mark bets as "won" or "lost" to track your performance accurately in your Portfolio.
          </li>
        </ul>
      </section>

      <section className="space-y-6">
        <h3 className="text-2xl font-bold border-b border-zinc-800 pb-2">4. Team & Player Search</h3>
        <p className="text-zinc-400">
          Explore detailed statistics for any team or player.
        </p>
        <ul className="list-disc list-inside space-y-2 text-zinc-400">
          <li>
            <strong>Team Search:</strong> Find teams and view their Elo ratings, attack/defense strengths, and historical performance.
          </li>
          <li>
            <strong>Player Search:</strong> Search for specific players to see their current team, nationality, and position.
          </li>
        </ul>
      </section>

      <section className="space-y-6">
        <h3 className="text-2xl font-bold border-b border-zinc-800 pb-2">5. Acca Builder</h3>
        <p className="text-zinc-400">
          Craft powerful accumulator bets with confidence.
        </p>
        <ul className="list-disc list-inside space-y-2 text-zinc-400">
          <li>
            Add selections from multiple matches to your accumulator slip.
          </li>
          <li>
            The builder automatically calculates total odds and potential returns.
          </li>
          <li>
            Generate booking codes for your preferred bookmaker (Bet9ja, SportyBet, 1xBet).
          </li>
        </ul>
      </section>

      <section className="space-y-6">
        <h3 className="text-2xl font-bold border-b border-zinc-800 pb-2">6. Portfolio</h3>
        <p className="text-zinc-400">
          Monitor your betting performance and bankroll growth.
        </p>
        <ul className="list-disc list-inside space-y-2 text-zinc-400">
          <li>
            Track active bets, total stake, win rate, and net profit.
          </li>
          <li>
            View your complete betting history.
          </li>
        </ul>
      </section>

      <section className="space-y-6">
        <h3 className="text-2xl font-bold border-b border-zinc-800 pb-2">7. Premium Hub</h3>
        <p className="text-zinc-400">
          Unlock the full potential of FootyEdge AI with a Premium subscription.
        </p>
        <ul className="list-disc list-inside space-y-2 text-zinc-400">
          <li>
            Access **Elite Signals** with enhanced insights and higher confidence levels.
          </li>
          <li>
            Receive exclusive Telegram alerts and configure your notification settings.
          </li>
          <li>
            View upcoming high-value matches identified through deeper AI analysis.
          </li>
          <li>
            Upgrade your plan via the "Pricing" section.
          </li>
        </ul>
      </section>
    </div>
  );
};

export default HowToUse;
