-- ============================================
-- FootyEdge AI Telegram transport state (Objective 9.1)
-- LOCAL migration only. NOT applied to production.
-- Backward-compatible: only ADDs three new tables/indexes/policies
-- surface; never drops, rewrites, backfills, or touches any existing
-- table (subscriptions, subscription_events, profiles), RLS posture,
-- function, grant, or Objective 7/8 identity data.
-- ============================================
--
-- SCOPE
-- 1. public.telegram_accounts: server-side mapping
--    telegram_user_id -> auth.users.id. Telegram username is display
--    metadata only and MUST NEVER be used as identity. One Telegram
--    account maps to at most one FootyEdge user and vice versa
--    (UNIQUE on both columns); conflicts are refused by the adapter,
--    never silently rebound.
-- 2. public.telegram_updates: durable, append-only record of Telegram
--    update_id deliveries for idempotent processing. UNIQUE
--    (telegram_update_id) is the concurrency boundary: exactly one
--    worker claims a delivery; duplicates short-circuit to 2xx with
--    no re-execution and no second response.
-- 3. public.telegram_link_tokens: one-time linking codes. Only the
--    SHA-256 hash is stored; plaintext never touches the database.
--    Tokens are short-lived, bound to one user_id, and consumed
--    atomically (single conditional UPDATE); consumed or expired
--    tokens can never link.
-- 4. RLS: enabled on all three tables with NO policies for
--    anon/authenticated, so ordinary clients can neither read mappings
--    nor write update/token records. service_role keeps its default
--    full rights for trusted server-side adapter processing.
-- 5. No seed rows. No Telegram bot/Webhook registration here.
--
-- ROLLBACK STANCE: forward-fix only. To revert, deploy a new
-- migration; do not edit this file after it has been applied
-- anywhere beyond a local scratch database.

-- ---------- 1. telegram_accounts ----------
CREATE TABLE IF NOT EXISTS public.telegram_accounts (
    id               BIGSERIAL PRIMARY KEY,
    user_id          UUID                     NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    telegram_user_id BIGINT                   NOT NULL,
    telegram_chat_id BIGINT                   NULL,
    telegram_username TEXT                    NULL,
    status           TEXT                     NOT NULL DEFAULT 'linked',
    linked_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at     TIMESTAMPTZ NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT telegram_accounts_user_id_key UNIQUE (user_id),
    CONSTRAINT telegram_accounts_telegram_user_id_key UNIQUE (telegram_user_id),
    CONSTRAINT telegram_accounts_status_check CHECK (status IN ('linked', 'unlinked'))
);

ALTER TABLE public.telegram_accounts ENABLE ROW LEVEL SECURITY;

-- Deny by default: strip default-privilege grants and grant nothing to
-- anon/authenticated. service_role keeps its default full rights for
-- trusted server-side adapter processing (table-owner path bypasses
-- RLS; no policy is needed for it, none is created for anyone else).
REVOKE ALL ON TABLE public.telegram_accounts FROM anon, authenticated;

-- ---------- 2. telegram_updates ----------
CREATE TABLE IF NOT EXISTS public.telegram_updates (
    id                BIGSERIAL PRIMARY KEY,
    telegram_update_id BIGINT                  NOT NULL,
    telegram_user_id  BIGINT                  NULL,
    account_id        BIGINT                  NULL REFERENCES public.telegram_accounts(id) ON DELETE SET NULL,
    processing_status TEXT                    NOT NULL,
    error_code        TEXT                    NULL,
    received_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at      TIMESTAMPTZ NULL,

    CONSTRAINT telegram_updates_update_id_key UNIQUE (telegram_update_id),
    CONSTRAINT telegram_updates_status_check CHECK (processing_status IN ('received', 'processed', 'ignored', 'failed'))
);

ALTER TABLE public.telegram_updates ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.telegram_updates FROM anon, authenticated;

CREATE INDEX IF NOT EXISTS telegram_updates_user_received_idx
    ON public.telegram_updates (telegram_user_id, received_at DESC);

-- ---------- 3. telegram_link_tokens ----------
CREATE TABLE IF NOT EXISTS public.telegram_link_tokens (
    token_hash  TEXT        PRIMARY KEY,
    user_id     UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at  TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ NULL
);

ALTER TABLE public.telegram_link_tokens ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.telegram_link_tokens FROM anon, authenticated;

CREATE INDEX IF NOT EXISTS telegram_link_tokens_user_idx
    ON public.telegram_link_tokens (user_id);

-- ---------- 4. updated_at maintenance (narrowly scoped) ----------
CREATE OR REPLACE FUNCTION public.handle_telegram_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_telegram_accounts_updated_at ON public.telegram_accounts;
CREATE TRIGGER trg_telegram_accounts_updated_at
    BEFORE UPDATE ON public.telegram_accounts
    FOR EACH ROW EXECUTE FUNCTION public.handle_telegram_updated_at();

-- Verification queries (read-only; run after apply in a non-prod context):
-- SELECT tablename, rowsecurity FROM pg_tables WHERE tablename IN ('telegram_accounts', 'telegram_updates', 'telegram_link_tokens');
-- SELECT policyname FROM pg_policies WHERE tablename IN ('telegram_accounts', 'telegram_updates', 'telegram_link_tokens');
-- SELECT conname FROM pg_constraint WHERE conrelid IN ('public.telegram_accounts'::regclass, 'public.telegram_updates'::regclass, 'public.telegram_link_tokens'::regclass);
-- SELECT indexname FROM pg_indexes WHERE tablename IN ('telegram_accounts', 'telegram_updates', 'telegram_link_tokens');
-- SELECT grantee, privilege_type FROM information_schema.role_table_grants WHERE table_name IN ('telegram_accounts', 'telegram_updates', 'telegram_link_tokens') AND grantee IN ('anon', 'authenticated');
--   -- expected: zero rows
