-- ============================================
-- FootyEdge AI webhook ordering guard (Objective 8.3)
-- LOCAL migration only. NOT applied to production.
-- Backward-compatible: only ADDs nullable columns/indexes and
-- extends public.apply_paystack_event with two OPTIONAL
-- (DEFAULT NULL) parameters; never drops, rewrites, or backfills.
-- Never edits 20261001000000_* or 20261001010000_*.
-- ============================================
--
-- SCOPE (per Objective 8.2 Decision 2 / 8.3 §3)
-- 1. Event identity is UNCHANGED: UNIQUE(provider, provider_event_id)
--    with provider_event_id = "evt_" + SHA-256 hex of the exact raw
--    delivery bytes. No canonicalization, no new identity algorithm.
-- 2. Ordering metadata is NULL-tolerant: Paystack sends no stable
--    top-level event sequence, so provider_occurred_at /
--    provider_sequence are populated only when the application finds
--    an authoritative provider timestamp in the payload (currently
--    `data.created_at`, then `data.paid_at`, then
--    `data.transaction_date`). Absence of metadata preserves the
--    pre-8.3 arrival-wins behavior; it never blocks application.
-- 3. Stale-event rule: when ordering metadata proves an incoming
--    event is older than the latest applied event for the same
--    subscription, the subscription update is skipped (the event row
--    is still recorded for audit, marked ignored/stale_event). A stale
--    event MUST NOT overwrite newer subscription state.
-- 4. Audit indexes for the owner/admin event reads.
--
-- ROLLBACK STANCE: forward-fix only. To revert, deploy a new
-- migration; do not edit this file after it has been applied
-- anywhere beyond a local scratch database.

-- ---------- 1. ordering columns (nullable, no backfill) ----------
ALTER TABLE public.subscription_events
    ADD COLUMN IF NOT EXISTS provider_occurred_at TIMESTAMPTZ NULL;

ALTER TABLE public.subscription_events
    ADD COLUMN IF NOT EXISTS provider_sequence TEXT NULL;

-- Subscription-side high-water marker: the newest provider timestamp
-- ever applied to this row. Compared against incoming events.
ALTER TABLE public.subscriptions
    ADD COLUMN IF NOT EXISTS last_applied_occurred_at TIMESTAMPTZ NULL;

-- ---------- 2. audit/order indexes ----------
CREATE INDEX IF NOT EXISTS subscription_events_subscription_created_idx
    ON public.subscription_events (subscription_id, created_at DESC);

CREATE INDEX IF NOT EXISTS subscription_events_provider_type_created_idx
    ON public.subscription_events (provider, event_type, created_at DESC);

CREATE INDEX IF NOT EXISTS subscription_events_occurred_idx
    ON public.subscription_events (provider, provider_occurred_at DESC);

-- -----------------------------------------------------------------------
-- public.apply_paystack_event(): extended with two OPTIONAL parameters.
-- The original 13 parameters keep their names, order and types; the two
-- new ones carry DEFAULT NULL so any caller still using the 13-argument
-- form keeps working. EXECUTE remains service_role-only.
-- -----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.apply_paystack_event(
    p_provider                 TEXT,
    p_provider_event_id        TEXT,
    p_event_type               TEXT,
    p_payload                  JSONB,
    p_processing_status        TEXT,
    p_error_code               TEXT,
    p_subscription_id          BIGINT,
    p_apply_subscription       BOOLEAN,
    p_new_status               TEXT,
    p_provider_customer_id     TEXT,
    p_provider_subscription_id TEXT,
    p_current_period_start     TIMESTAMPTZ,
    p_current_period_end       TIMESTAMPTZ,
    p_provider_occurred_at     TIMESTAMPTZ DEFAULT NULL,
    p_provider_sequence        TEXT DEFAULT NULL
)
RETURNS TABLE (event_id BIGINT, inserted BOOLEAN)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_event_id BIGINT;
    v_last_applied TIMESTAMPTZ;
BEGIN
    INSERT INTO public.subscription_events (
        subscription_id, provider, provider_event_id, event_type, payload,
        processing_status, error_code, provider_occurred_at,
        provider_sequence
    )
    VALUES (
        p_subscription_id, p_provider, p_provider_event_id, p_event_type,
        COALESCE(p_payload, '{}'::jsonb), p_processing_status, p_error_code,
        p_provider_occurred_at, p_provider_sequence
    )
    ON CONFLICT (provider, provider_event_id) DO NOTHING
    RETURNING id INTO v_event_id;

    IF v_event_id IS NULL THEN
        -- Already recorded: a duplicate delivery. No mutation of anything.
        RETURN QUERY SELECT NULL::BIGINT, false;
        RETURN;
    END IF;

    IF COALESCE(p_apply_subscription, false)
       AND p_subscription_id IS NOT NULL
       AND p_new_status IS NOT NULL THEN
        -- Stale-event guard (NULL-tolerant): skip the subscription update
        -- only when BOTH the stored marker and the incoming timestamp are
        -- known AND the incoming event is strictly older. In every other
        -- case (either side NULL, equal, or newer) apply normally.
        SELECT s.last_applied_occurred_at INTO v_last_applied
          FROM public.subscriptions AS s
         WHERE s.id = p_subscription_id;

        IF v_last_applied IS NULL
           OR p_provider_occurred_at IS NULL
           OR p_provider_occurred_at >= v_last_applied THEN
            UPDATE public.subscriptions AS s
               SET status                   = p_new_status,
                   provider                 = COALESCE(p_provider, s.provider),
                   provider_customer_id     = COALESCE(p_provider_customer_id, s.provider_customer_id),
                   provider_subscription_id = COALESCE(p_provider_subscription_id, s.provider_subscription_id),
                   current_period_start     = COALESCE(p_current_period_start, s.current_period_start),
                   current_period_end       = COALESCE(p_current_period_end, s.current_period_end),
                   last_applied_occurred_at = GREATEST(
                       COALESCE(s.last_applied_occurred_at, p_provider_occurred_at),
                       p_provider_occurred_at)
             WHERE s.id = p_subscription_id
               AND s.provider = p_provider;
        ELSE
            -- Provably stale: leave the subscription untouched and mark
            -- the recorded event so the audit trail shows why nothing
            -- changed.
            UPDATE public.subscription_events
               SET processing_status = 'ignored',
                   error_code = 'stale_event'
             WHERE id = v_event_id;
            IF p_processing_status IN ('processed', 'ignored', 'failed') THEN
                UPDATE public.subscription_events
                   SET processed_at = now()
                 WHERE id = v_event_id;
            END IF;
            RETURN QUERY SELECT v_event_id, true;
            RETURN;
        END IF;
    END IF;

    IF p_processing_status IN ('processed', 'ignored', 'failed') THEN
        UPDATE public.subscription_events
           SET processed_at = now()
         WHERE id = v_event_id;
    END IF;

    RETURN QUERY SELECT v_event_id, true;
END;
$$;

REVOKE ALL ON FUNCTION public.apply_paystack_event(
    TEXT, TEXT, TEXT, JSONB, TEXT, TEXT, BIGINT, BOOLEAN, TEXT, TEXT, TEXT,
    TIMESTAMPTZ, TIMESTAMPTZ, TIMESTAMPTZ, TEXT
) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.apply_paystack_event(
    TEXT, TEXT, TEXT, JSONB, TEXT, TEXT, BIGINT, BOOLEAN, TEXT, TEXT, TEXT,
    TIMESTAMPTZ, TIMESTAMPTZ, TIMESTAMPTZ, TEXT
) TO service_role;

-- Verification queries (read-only; run after apply in a non-prod context):
-- SELECT column_name, data_type FROM information_schema.columns
--   WHERE table_name IN ('subscription_events', 'subscriptions')
--   AND column_name IN ('provider_occurred_at', 'provider_sequence', 'last_applied_occurred_at');
-- SELECT indexname FROM pg_indexes WHERE tablename = 'subscription_events';
-- SELECT has_function_privilege('anon', 'public.apply_paystack_event(text,text,text,jsonb,text,text,bigint,boolean,text,text,text,timestamptz,timestamptz,timestamptz,text)', 'EXECUTE') AS anon_may_call;
--   -- expected: false
-- SELECT has_function_privilege('service_role', 'public.apply_paystack_event(text,text,text,jsonb,text,text,bigint,boolean,text,text,text,timestamptz,timestamptz,timestamptz,text)', 'EXECUTE') AS service_may_call;
--   -- expected: true
