-- ============================================
-- FootyEdge AI WhatsApp transport adapter state.
--
-- Mirrors supabase/migrations/20261004000000_telegram_adapter.sql:
-- account mappings, delivery idempotency, one-time link tokens, plus
-- opt-in notification preferences and an idempotent notification
-- outbox. Answers:
--   "which FootyEdge user owns this WhatsApp number?"
--   "was this Meta delivery already processed?"
--   "may this user receive this notification category?"
--   "was this notification already queued/sent?"
--
-- Phone numbers are TEXT (E.164 digits, optional leading +), never
-- BIGINT: leading zeros and "+" must survive storage verbatim.
-- A WhatsApp number is NEVER proof of account identity; linkage
-- happens only through consumed link tokens (see whatsapp_api.py).
--
-- Deliberately unseeded and UNAPPLIED: apply only under a reviewed
-- migration plan with explicit authorization. No RLS policies for
-- anon/authenticated (service_role server processing only).
-- ROLLBACK STANCE: forward-fix only once applied. The commented
-- ROLLBACK block at the end of this file reverts a scratch apply;
-- do not edit this file after production apply.
-- ============================================

-- ---------- 1. whatsapp_accounts ----------
CREATE TABLE IF NOT EXISTS public.whatsapp_accounts (
    id               BIGSERIAL PRIMARY KEY,
    user_id          UUID                     NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    whatsapp_user_id TEXT                     NOT NULL,
    display_name     TEXT                     NULL,
    status           TEXT                     NOT NULL DEFAULT 'linked',
    linked_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at     TIMESTAMPTZ NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT whatsapp_accounts_user_id_key UNIQUE (user_id),
    CONSTRAINT whatsapp_accounts_whatsapp_user_id_key UNIQUE (whatsapp_user_id),
    CONSTRAINT whatsapp_accounts_status_check CHECK (status IN ('linked', 'unlinked'))
);

ALTER TABLE public.whatsapp_accounts ENABLE ROW LEVEL SECURITY;

-- Deny by default: strip default-privilege grants and grant nothing to
-- anon/authenticated. service_role keeps its default full rights for
-- trusted server-side adapter processing (table-owner path bypasses
-- RLS; no policy is needed for it, none is created for anyone else).
REVOKE ALL ON TABLE public.whatsapp_accounts FROM anon, authenticated;

-- ---------- 2. whatsapp_updates ----------
CREATE TABLE IF NOT EXISTS public.whatsapp_updates (
    id                BIGSERIAL PRIMARY KEY,
    whatsapp_message_id TEXT                  NOT NULL,
    whatsapp_user_id  TEXT                    NULL,
    account_id        BIGINT                  NULL REFERENCES public.whatsapp_accounts(id) ON DELETE SET NULL,
    processing_status TEXT                    NOT NULL,
    error_code        TEXT                    NULL,
    received_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at      TIMESTAMPTZ NULL,

    CONSTRAINT whatsapp_updates_message_id_key UNIQUE (whatsapp_message_id),
    CONSTRAINT whatsapp_updates_status_check CHECK (processing_status IN ('received', 'processed', 'ignored', 'failed'))
);

ALTER TABLE public.whatsapp_updates ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.whatsapp_updates FROM anon, authenticated;

CREATE INDEX IF NOT EXISTS whatsapp_updates_user_received_idx
    ON public.whatsapp_updates (whatsapp_user_id, received_at DESC);

-- ---------- 3. whatsapp_link_tokens ----------
CREATE TABLE IF NOT EXISTS public.whatsapp_link_tokens (
    token_hash  TEXT        PRIMARY KEY,
    user_id     UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at  TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ NULL
);

ALTER TABLE public.whatsapp_link_tokens ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.whatsapp_link_tokens FROM anon, authenticated;

CREATE INDEX IF NOT EXISTS whatsapp_link_tokens_user_idx
    ON public.whatsapp_link_tokens (user_id);

-- ---------- 4. whatsapp_preferences ----------
-- Explicit opt-in per notification category. No row, or all-false row,
-- means fully opted out (default-disabled, never assumed consent).
CREATE TABLE IF NOT EXISTS public.whatsapp_preferences (
    user_id           UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    match_updates     BOOLEAN     NOT NULL DEFAULT FALSE,
    prediction_alerts BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT whatsapp_preferences_user_id_key UNIQUE (user_id)
);

ALTER TABLE public.whatsapp_preferences ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.whatsapp_preferences FROM anon, authenticated;

-- ---------- 5. whatsapp_deliveries (notification outbox) ----------
-- One row per (category, entity, user). UNIQUE(idempotency_key) is the
-- duplicate arbiter: concurrent collectors/inserts for the same
-- notification collapse to a single row. Lifecycle: pending ->
-- sending -> sent | failed, with bounded attempts and claim leases
-- (claimed_until). Abandoned sending rows (lease expired) become
-- claimable again; ambiguous provider timeouts return the row to
-- pending with attempts incremented and last_error set, explicitly
-- NOT counted as sent (at-least-once, never claimed exactly-once).
CREATE TABLE IF NOT EXISTS public.whatsapp_deliveries (
    id                 BIGSERIAL PRIMARY KEY,
    idempotency_key    TEXT        NOT NULL,
    user_id            UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    category           TEXT        NOT NULL,
    entity_type        TEXT        NULL,
    entity_id          TEXT        NULL,
    payload_hash       TEXT        NULL,
    body               TEXT        NULL,
    status             TEXT        NOT NULL DEFAULT 'pending',
    attempts           INTEGER     NOT NULL DEFAULT 0,
    max_attempts       INTEGER     NOT NULL DEFAULT 3,
    claimed_until      TIMESTAMPTZ NULL,
    provider_message_id TEXT       NULL,
    provider_status    TEXT        NULL,
    last_error         TEXT        NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    sent_at            TIMESTAMPTZ NULL,

    CONSTRAINT whatsapp_deliveries_key_key UNIQUE (idempotency_key),
    CONSTRAINT whatsapp_deliveries_category_check CHECK (category IN ('match_update', 'prediction_alert')),
    CONSTRAINT whatsapp_deliveries_status_check CHECK (status IN ('pending', 'sending', 'sent', 'failed'))
);

ALTER TABLE public.whatsapp_deliveries ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.whatsapp_deliveries FROM anon, authenticated;

CREATE INDEX IF NOT EXISTS whatsapp_deliveries_claim_idx
    ON public.whatsapp_deliveries (status, claimed_until, attempts);

CREATE INDEX IF NOT EXISTS whatsapp_deliveries_user_idx
    ON public.whatsapp_deliveries (user_id);

-- ---------- 6. atomic outbox claim (production concurrency boundary) ----------
-- Single-call claim for whatsapp_deliveries: SELECT ... FOR UPDATE SKIP
-- LOCKED + conditional UPDATE in one function invocation, so two
-- concurrent workers can never receive the same delivery. Narrowly scoped
-- to whatsapp_deliveries only: claims one eligible row (pending, or
-- sending with an expired lease), subject to attempts < max_attempts.
-- Sets status='sending', claimed_until=p_lease_until, attempts+1, and
-- returns the complete claimed row (0 rows when no eligible delivery).
-- Never claims sent/failed rows or exhausted (attempts >= max_attempts)
-- rows. Ambiguous provider timeouts are NOT resolved here: the caller
-- returns the row to pending with attempts incremented and last_error
-- set (at-least-once, never claimed exactly-once). Idempotency still
-- rests on UNIQUE(idempotency_key) at insert time; this function only
-- arbitrates the pending->sending claim.
CREATE OR REPLACE FUNCTION public.claim_whatsapp_delivery(
    p_now TIMESTAMPTZ,
    p_lease_until TIMESTAMPTZ
)
RETURNS SETOF public.whatsapp_deliveries
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_id BIGINT;
BEGIN
    SELECT d.id INTO v_id
    FROM public.whatsapp_deliveries AS d
    WHERE d.attempts < d.max_attempts
      AND (
            d.status = 'pending'
         OR (d.status = 'sending'
             AND (d.claimed_until IS NULL OR d.claimed_until <= p_now))
          )
    ORDER BY d.id
    FOR UPDATE SKIP LOCKED
    LIMIT 1;

    IF v_id IS NULL THEN
        RETURN;
    END IF;

    RETURN QUERY
    UPDATE public.whatsapp_deliveries AS d
    SET status = 'sending',
        claimed_until = p_lease_until,
        attempts = d.attempts + 1
    WHERE d.id = v_id
      AND d.attempts < d.max_attempts
      AND (
            d.status = 'pending'
         OR (d.status = 'sending'
             AND (d.claimed_until IS NULL OR d.claimed_until <= p_now))
          )
    RETURNING d.*;
END;
$$;

-- Service-role only: the claim function runs server-side. No anon/
-- authenticated access (deny by default, matching the tables above).
REVOKE ALL ON FUNCTION public.claim_whatsapp_delivery(TIMESTAMPTZ, TIMESTAMPTZ) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_whatsapp_delivery(TIMESTAMPTZ, TIMESTAMPTZ) TO service_role;

-- ---------- 7. updated_at maintenance (narrowly scoped) ----------
CREATE OR REPLACE FUNCTION public.handle_whatsapp_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_whatsapp_accounts_updated_at ON public.whatsapp_accounts;
CREATE TRIGGER trg_whatsapp_accounts_updated_at
    BEFORE UPDATE ON public.whatsapp_accounts
    FOR EACH ROW EXECUTE FUNCTION public.handle_whatsapp_updated_at();

DROP TRIGGER IF EXISTS trg_whatsapp_preferences_updated_at ON public.whatsapp_preferences;
CREATE TRIGGER trg_whatsapp_preferences_updated_at
    BEFORE UPDATE ON public.whatsapp_preferences
    FOR EACH ROW EXECUTE FUNCTION public.handle_whatsapp_updated_at();

DROP TRIGGER IF EXISTS trg_whatsapp_deliveries_updated_at ON public.whatsapp_deliveries;
CREATE TRIGGER trg_whatsapp_deliveries_updated_at
    BEFORE UPDATE ON public.whatsapp_deliveries
    FOR EACH ROW EXECUTE FUNCTION public.handle_whatsapp_updated_at();

-- Verification queries (read-only; run after apply in a non-prod context):
-- SELECT tablename, rowsecurity FROM pg_tables WHERE tablename IN ('whatsapp_accounts', 'whatsapp_updates', 'whatsapp_link_tokens', 'whatsapp_preferences', 'whatsapp_deliveries');
-- SELECT policyname FROM pg_policies WHERE tablename IN ('whatsapp_accounts', 'whatsapp_updates', 'whatsapp_link_tokens', 'whatsapp_preferences', 'whatsapp_deliveries');
--   -- expected: zero rows
-- SELECT conname FROM pg_constraint WHERE conrelid IN ('public.whatsapp_accounts'::regclass, 'public.whatsapp_updates'::regclass, 'public.whatsapp_link_tokens'::regclass, 'public.whatsapp_preferences'::regclass, 'public.whatsapp_deliveries'::regclass);
-- SELECT indexname FROM pg_indexes WHERE tablename IN ('whatsapp_accounts', 'whatsapp_updates', 'whatsapp_link_tokens', 'whatsapp_preferences', 'whatsapp_deliveries');
-- SELECT grantee, privilege_type FROM information_schema.role_table_grants WHERE table_name IN ('whatsapp_accounts', 'whatsapp_updates', 'whatsapp_link_tokens', 'whatsapp_preferences', 'whatsapp_deliveries') AND grantee IN ('anon', 'authenticated');
--   -- expected: zero rows
-- SELECT proname FROM pg_proc WHERE proname = 'claim_whatsapp_delivery';
-- SELECT grantee, privilege_type FROM information_schema.role_routine_grants WHERE routine_name = 'claim_whatsapp_delivery';
--   -- expected: service_role EXECUTE only; zero rows for anon/authenticated

-- ROLLBACK (scratch/local only; forward-fix after any real apply):
-- DROP FUNCTION IF EXISTS public.claim_whatsapp_delivery(TIMESTAMPTZ, TIMESTAMPTZ);
-- DROP TRIGGER IF EXISTS trg_whatsapp_deliveries_updated_at ON public.whatsapp_deliveries;
-- DROP TRIGGER IF EXISTS trg_whatsapp_preferences_updated_at ON public.whatsapp_preferences;
-- DROP TRIGGER IF EXISTS trg_whatsapp_accounts_updated_at ON public.whatsapp_accounts;
-- DROP FUNCTION IF EXISTS public.handle_whatsapp_updated_at();
-- DROP TABLE IF EXISTS public.whatsapp_deliveries;
-- DROP TABLE IF EXISTS public.whatsapp_preferences;
-- DROP TABLE IF EXISTS public.whatsapp_link_tokens;
-- DROP TABLE IF EXISTS public.whatsapp_updates;
-- DROP TABLE IF EXISTS public.whatsapp_accounts;
